server:
  port: 9001 

spring:
 thymeleaf:
  cache: false
 jpa:
  database: POSTGRESQL
  show-sql: true
  ddl-auto: update
  properties.hibernate.jdbc.lob.non_contextual_creation: true
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/pncti
  username: postgres
  password: maxmin
